title:              Elliot Voris
email:              elliot@voris.me
description:        I'm Elliot. I'm your friend.
author:             Elliot Voris
baseurl:            ""
url:                "https://www.elliotfriend.com"

# Social Profiles
twitter_username:   elliotfriend
github_username:    elliotfriend
facebook_username:  elliotfriend
youtube_username:   elliotfriend
instagram_username: elliotfriend

# Build settings
permalink:          /post/:year/:month/:day/:title
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate