title:             Elliot Voris
email:             elliot@voris.me
description:       Faith. Family. Curiosity.
author:            Start Bootstrap
baseurl:           ""
url:               "http://www.elliotfriend.com"

# Social Profiles
twitter_username:  elliotfriend
github_username:   elliotfriend
facebook_username: elliotfriend

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
